apiVersion: v1
kind: ServiceAccount
metadata:
  name: hornet
  namespace: hornet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hornet-role
  namespace: hornet
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hornet-rolebinding
  namespace: hornet
subjects:
  - kind: ServiceAccount
    name: hornet
    namespace: hornet
roleRef:
  kind: Role
  name: hornet-role
  apiGroup: rbac.authorization.k8s.io
